import React, { useState } from 'react';
import { ArrowRight, Calendar, Check, Clipboard, Headphones, Linkedin, MessageCircle, Play, UserRound } from 'lucide-react';
import { PageRoute } from '../types';
import { coreSkills, keyAchievements, personalInfo, testimonials } from '../data/flynnData';

export default function HomePage({ onNavigate, onOpenBooking, onOpenResume }: { onNavigate:(p:PageRoute)=>void; onOpenBooking:()=>void; onOpenResume:()=>void }) {
 const [roleModal,setRoleModal]=useState<'Part-Time'|'Full-Time'|null>(null);
 const [copied,setCopied]=useState(false);
 const copyDiscord=()=>{navigator.clipboard?.writeText('flynn30');setCopied(true);setTimeout(()=>setCopied(false),1200)};
 return <div className="overflow-hidden">
  <section className="hero relative"><div className="hero-glow one"/><div className="hero-glow two"/><div className="mx-auto grid max-w-7xl items-center gap-12 px-4 pb-20 pt-32 sm:px-6 lg:grid-cols-[1.15fr_.85fr] lg:pb-28 lg:pt-40"><div className="relative z-10"><div className="eyebrow">Senior SDR · B2B Cold Caller · Appointment Setter</div><h1 className="mt-5 text-5xl font-black leading-[.92] tracking-tight sm:text-6xl lg:text-8xl">COLD CALLS.<br/><span className="text-brand">QUALIFIED MEETINGS.</span><br/>REAL PIPELINE.</h1><p className="mt-7 max-w-2xl text-base leading-7 text-slate-600 sm:text-lg">{personalInfo.tagline} {personalInfo.executiveSummary}</p><div className="mt-8 flex flex-wrap gap-3"><button onClick={onOpenBooking} className="btn-primary"> <Calendar size={16}/> Confim Schedule</button><button onClick={()=>onNavigate('calls')} className="btn-secondary"><Headphones size={16}/> Hear My Opener</button><button onClick={onOpenResume} className="btn-ghost">View Resume <ArrowRight size={15}/></button></div><div className="mt-7 flex flex-wrap gap-3 text-sm"><a href={personalInfo.linkedin} target="_blank" rel="noreferrer" className="social-chip"><Linkedin size={15}/> LinkedIn</a><a href="https://discord.com/" target="_blank" rel="noreferrer" className="social-chip"><MessageCircle size={15}/> flynn30</a><button onClick={copyDiscord} className="social-chip"><Clipboard size={15}/> {copied?'Copied':'Copy Discord'}</button></div></div><div className="relative"><div className="portrait-frame"><img src={personalInfo.heroImage} alt="Flynn working in a professional home-office setup"/><div className="portrait-tag"><span className="status-dot"/> Available for remote SDR opportunities</div></div><div className="scribble">Flynn</div></div></div></section>
  <section className="border-y border-slate-200 bg-white"><div className="mx-auto grid max-w-7xl grid-cols-2 divide-x divide-y divide-slate-200 sm:grid-cols-3 lg:grid-cols-6 lg:divide-y-0">{keyAchievements.map(a=><div key={a.label} className="metric"><strong>{a.value}</strong><span>{a.label}</span><small>{a.detail}</small></div>)}</div></section>
  <section className="section"><div className="mx-auto max-w-7xl px-4 sm:px-6"><div className="section-head"><div><p className="eyebrow">What I do</p><h2>Outbound execution built around quality.</h2></div><p>I focus on the part of the sales process where strong phone skills, research, qualification, and consistency create the next real opportunity.</p></div><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">{[['01','Prospect','Build targeted lists around the ICP and reach decision-makers through phone, LinkedIn, and email.'],['02','Connect','Open naturally, earn attention quickly, and navigate gatekeepers without sounding scripted.'],['03','Qualify','Use practical discovery and BANT-style questions to separate interest from genuine fit.'],['04','Book','Confirm the right person, reason, timing, and next step before handing the meeting to the sales team.']].map(([n,t,d])=><div className="service-card" key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></div>)}</div></div></section>
  <section className="section bg-slate-950 text-white"><div className="mx-auto grid max-w-7xl gap-12 px-4 sm:px-6 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><p className="eyebrow text-sky-300">Hear the work</p><h2 className="text-4xl font-black sm:text-5xl">Real outbound conversations. Real techniques.</h2><p className="mt-5 text-slate-400">Hear examples of my opening, objection handling, qualification, and meeting-setting approach.</p><button onClick={()=>onNavigate('calls')} className="btn-primary mt-7">Hear My Opener <Play size={15}/></button></div><div className="grid gap-3">{['Permission-based opener','Reschedule recovery','Objection de-escalation','Qualification before booking'].map((x,i)=><button onClick={()=>onNavigate('calls')} key={x} className="flex items-center justify-between rounded-2xl border border-white/10 bg-white/5 p-5 text-left hover:bg-white/10"><span><small className="text-sky-300">0{i+1}</small><strong className="mt-1 block text-lg">{x}</strong></span><ArrowRight/></button>)}</div></div></section>
  <section className="section"><div className="mx-auto max-w-7xl px-4 sm:px-6"><div className="section-head"><div><p className="eyebrow">Proof</p><h2>What peers & leaders say.</h2></div><p>Feedback focused on the skills that matter in an SDR seat: phone discipline, qualification, objection handling, and pipeline creation.</p></div><div className="grid gap-5 md:grid-cols-3">{testimonials.map(t=><article className="testimonial" key={t.name}><img src={t.image} alt={`${t.name} — ${t.role}`}/><p>“{t.quote}”</p><footer><strong>{t.name}</strong><span>{t.role} · {t.company}</span></footer></article>)}</div></div></section>
  <section className="section bg-slate-50"><div className="mx-auto max-w-7xl px-4 sm:px-6"><div className="section-head"><div><p className="eyebrow">Core stack</p><h2>Built for outbound teams.</h2></div><button onClick={()=>onNavigate('experience')} className="btn-secondary">See Experience <ArrowRight size={15}/></button></div><div className="flex flex-wrap gap-2">{coreSkills.map(s=><span key={s} className="skill-pill">{s}</span>)}</div></div></section>
  <section className="section"><div className="mx-auto max-w-5xl px-4 text-center sm:px-6"><div className="rounded-[2rem] border border-slate-200 bg-white p-8 shadow-xl sm:p-12"><UserRound className="mx-auto mb-5 text-brand" size={30}/><p className="eyebrow justify-center">Looking for my next Senior SDR role</p><h2 className="mt-3 text-4xl font-black">Part-Time or Full-Time.</h2><p className="mx-auto mt-4 max-w-2xl text-slate-600">If you need someone who can own the first conversation, qualify the right prospects, and consistently put qualified meetings on the calendar, let’s talk.</p><div className="mt-7 flex flex-wrap justify-center gap-3"><button onClick={()=>setRoleModal('Part-Time')} className="btn-secondary">Part-Time SDR</button><button onClick={()=>setRoleModal('Full-Time')} className="btn-primary">Full-Time SDR</button></div></div></div></section>
  {roleModal&&<div className="fixed inset-0 z-[90] grid place-items-center bg-slate-950/60 p-4"><div className="w-full max-w-md rounded-3xl bg-white p-7 shadow-2xl"><div className="flex justify-between"><div><p className="eyebrow">{roleModal} option</p><h3 className="text-3xl font-black">Let’s discuss the fit.</h3></div><button onClick={()=>setRoleModal(null)} className="text-slate-400">×</button></div><p className="mt-4 text-sm leading-6 text-slate-600">Tell Flynn your target market, hours, and appointment-setting goals. The scheduling form captures the details needed for a productive first conversation.</p><button onClick={()=>{setRoleModal(null);onOpenBooking()}} className="btn-primary mt-6 w-full justify-center">Start Inquiry <ArrowRight size={15}/></button></div></div>}
 </div>
}
