import React, { useMemo, useState } from 'react';
import { X, Calendar, Clock, CheckCircle2, Send } from 'lucide-react';
import { ScheduleFormData } from '../types';
import { personalInfo } from '../data/flynnData';

const dates = Array.from({length: 7}, (_, i) => { const d = new Date(); d.setDate(d.getDate()+i+1); return d; });
const times = ['9:00 AM','10:00 AM','11:00 AM','1:00 PM','2:00 PM','3:00 PM','4:00 PM'];
const inquiryTypes = ['Senior SDR role','Part-time SDR role','Full-time SDR role','Outbound / appointment-setting project','General inquiry'];

const formatDate = (d: Date) => d.toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric',year:'numeric'});

function templateA(data: ScheduleFormData) {
  return `NEW FLYNN INTRO INQUIRY\n\nFull name: ${data.fullName}\nEmail: ${data.email}\nCompany: ${data.company || 'Not provided'}\nRole: ${data.role || 'Not provided'}\nInquiry type: ${data.inquiryType}\nPart-time/full-time preference: ${data.employmentPreference}\nSelected date: ${data.selectedDate}\nSelected time: ${data.selectedTime}\nMessage: ${data.message || 'Not provided'}\nConsent status: ${data.consent ? 'Yes' : 'No'}\nSubmission timestamp: ${data.submissionTimestamp}`;
}
function templateB(data: ScheduleFormData) {
  return `Hi ${data.fullName},\n\nThanks for reaching out to Flynn. Your 15-minute intro request has been received.\n\nSubmitted details:\n• Company: ${data.company || 'Not provided'}\n• Role: ${data.role || 'Not provided'}\n• Inquiry: ${data.inquiryType}\n• Preference: ${data.employmentPreference}\n• Selected date: ${data.selectedDate}\n• Selected time: ${data.selectedTime}\n• Message: ${data.message || 'Not provided'}\n\nNext step: Flynn will review the request and confirm the meeting details directly.\n\nBest,\nFlynn James Q. Pontino\nSenior SDR\n${personalInfo.email}`;
}

async function sendEmailJS(templateId: string, data: ScheduleFormData, body: string) {
  const serviceId = import.meta.env.VITE_EMAILJS_SERVICE_ID;
  const publicKey = import.meta.env.VITE_EMAILJS_PUBLIC_KEY;
  if (!serviceId || !publicKey || !templateId) return false;
  const payload = { service_id: serviceId, template_id: templateId, user_id: publicKey, template_params: { ...data, body, to_email: personalInfo.email, prospect_email: data.email, timestamp: data.submissionTimestamp } };
  const res = await fetch('https://api.emailjs.com/api/v1.0/email/send', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(payload) });
  return res.ok;
}

export default function BookingModal({ isOpen, onClose, initialPreference }: { isOpen:boolean; onClose:()=>void; initialPreference?:'Part-Time'|'Full-Time' }) {
  const [preference,setPreference] = useState<'Part-Time'|'Full-Time'>(initialPreference || 'Full-Time');
  const [fullName,setFullName] = useState(''); const [email,setEmail] = useState(''); const [company,setCompany] = useState(''); const [role,setRole] = useState('');
  const [inquiryType,setInquiryType] = useState('Senior SDR role'); const [selectedDate,setSelectedDate] = useState(formatDate(dates[0])); const [selectedTime,setSelectedTime] = useState(times[1]); const [message,setMessage] = useState(''); const [consent,setConsent] = useState(false); const [sent,setSent] = useState(false); const [loading,setLoading] = useState(false); const [error,setError] = useState('');
  const dateOptions = useMemo(()=>dates.map(formatDate),[]);
  if (!isOpen) return null;
  const submit = async (e:React.FormEvent) => { e.preventDefault(); setError(''); if(!consent){setError('Please provide consent before submitting.');return;} setLoading(true); const data:ScheduleFormData={fullName,email,company,role,inquiryType,employmentPreference:preference,selectedDate,selectedTime,message,consent,submissionTimestamp:new Date().toISOString()}; try { const a=await sendEmailJS(import.meta.env.VITE_EMAILJS_OWNER_TEMPLATE_ID,data,templateA(data)); const b=await sendEmailJS(import.meta.env.VITE_EMAILJS_PROSPECT_TEMPLATE_ID,data,templateB(data)); if(!a || !b){ const subject=encodeURIComponent(`15-Minute Intro Request — ${fullName}`); const body=encodeURIComponent(templateA(data)); window.location.href=`mailto:${personalInfo.email}?subject=${subject}&body=${body}`; } setSent(true); } catch { setError('The form could not send automatically. Your email app has been opened with the complete inquiry details.'); const subject=encodeURIComponent(`15-Minute Intro Request — ${fullName}`); const body=encodeURIComponent(templateA(data)); window.location.href=`mailto:${personalInfo.email}?subject=${subject}&body=${body}`; } finally { setLoading(false); } };
  const reset=()=>{setSent(false);setError('');};
  return <div className="modal-backdrop"><div className="modal booking-modal"><button className="modal-close" onClick={onClose}><X/></button>{sent?<div className="success-state"><CheckCircle2 size={48}/><p className="eyebrow">Request Received</p><h2>Thanks, {fullName.split(' ')[0] || 'there'}.</h2><p>Your selected slot and submitted details have been captured. Flynn will confirm the meeting directly.</p><div className="summary-card"><div><b>Date</b><span>{selectedDate}</span></div><div><b>Time</b><span>{selectedTime}</span></div><div><b>Preference</b><span>{preference}</span></div></div><button className="btn btn-primary" onClick={reset}>Submit Another Inquiry</button></div>:<form onSubmit={submit}><p className="eyebrow">Schedule 15-Minute Intro</p><h2>Tell Flynn what you need.</h2><p className="modal-copy">Choose a schedule, tell Flynn about the opportunity, and receive a clear confirmation.</p><div className="form-grid"><label>Full name<input required value={fullName} onChange={e=>setFullName(e.target.value)} /></label><label>Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} /></label><label>Company<input value={company} onChange={e=>setCompany(e.target.value)} /></label><label>Role<input value={role} onChange={e=>setRole(e.target.value)} placeholder="Founder, Head of Sales, Recruiter…" /></label><label>Inquiry type<select value={inquiryType} onChange={e=>setInquiryType(e.target.value)}>{inquiryTypes.map(x=><option key={x}>{x}</option>)}</select></label><label>Preference<select value={preference} onChange={e=>setPreference(e.target.value as 'Part-Time'|'Full-Time')}><option>Full-Time</option><option>Part-Time</option></select></label><label><span><Calendar size={14}/> Selected date</span><select value={selectedDate} onChange={e=>setSelectedDate(e.target.value)}>{dateOptions.map(x=><option key={x}>{x}</option>)}</select></label><label><span><Clock size={14}/> Selected time</span><select value={selectedTime} onChange={e=>setSelectedTime(e.target.value)}>{times.map(x=><option key={x}>{x}</option>)}</select></label></div><label>Message<textarea rows={4} value={message} onChange={e=>setMessage(e.target.value)} placeholder="Campaign, target market, role scope, or anything Flynn should know…" /></label><label className="consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} required /><span>I'm okay with Flynn emailing me about my inquiry. No spam, ever.</span></label>{error&&<p className="form-error">{error}</p>}<button className="btn btn-primary btn-wide" disabled={loading}>{loading?<><span className="spinner"/> Sending…</>:<><Send size={15}/> Confirm Schedule</>}</button><p className="form-note">Your submission includes the selected schedule, inquiry details, consent status, and timestamp.</p></form>}</div></div>;
}
