import React, { useRef, useState } from 'react';
import { Play, Pause, Volume2, ChevronDown } from 'lucide-react';
import { callRecordings } from '../data/flynnData';

const audioUrls = [import.meta.env.VITE_AUDIO_CALL_1_URL, import.meta.env.VITE_AUDIO_CALL_2_URL, import.meta.env.VITE_AUDIO_CALL_3_URL, import.meta.env.VITE_AUDIO_CALL_4_URL].map(v => v || '');

export default function ColdCallVault() {
 const [active,setActive]=useState<string|null>(null); const [expanded,setExpanded]=useState<string|null>(null); const [error,setError]=useState<string|null>(null); const refs=useRef<Record<string,HTMLAudioElement|null>>({});
 const toggle=(id:string,i:number)=>{const audio=refs.current[id]; if(!audio || !audioUrls[i]) {setError('This recording URL is not configured yet. Add the supplied audio URL to the matching VITE_AUDIO_CALL_*_URL variable.'); return;} if(active===id){audio.paused?audio.play():audio.pause();}else{Object.keys(refs.current).forEach(key=>refs.current[key]?.pause()); setActive(id); audio.currentTime=0; audio.play().catch(()=>setError('The audio could not be played. Check the recording URL and file permissions.'));}};
 return <div className="space-y-6">{callRecordings.map((call,i)=><article key={call.id} className="bg-white border border-[#dededb] rounded-2xl p-5 sm:p-7 shadow-xs"><div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4"><div><div className="text-[10px] uppercase font-display font-extrabold tracking-widest text-[#0077b6]">{call.skillTag}</div><h2 className="text-xl sm:text-2xl font-black uppercase font-display mt-1">{call.title}</h2><p className="text-xs text-zinc-500 mt-1">{call.company} · {call.industry} · {call.duration}</p></div><button type="button" onClick={()=>toggle(call.id,i)} className="shrink-0 px-5 py-3 bg-[#0077b6] text-white rounded-xl text-xs font-display font-extrabold uppercase flex items-center justify-center gap-2">{active===call.id && refs.current[call.id] && !refs.current[call.id]?.paused ? <Pause className="w-4 h-4"/>:<Play className="w-4 h-4"/>}{active===call.id?'Pause':'Play'} Recording</button></div><audio ref={el=>{refs.current[call.id]=el}} src={audioUrls[i] || undefined} preload="none" onPlay={()=>setActive(call.id)} onPause={()=>active===call.id&&setActive(null)} onError={()=>setError('Audio source unavailable. Please verify the supplied recording URL.')} controls className="w-full mt-5 h-10"/><div className="mt-4 grid grid-cols-1 sm:grid-cols-3 gap-3 text-xs"><div className="p-3 bg-[#f7f7f6] rounded-xl"><strong className="block uppercase font-display">Outcome</strong><span className="text-zinc-600">{call.outcome}</span></div><div className="p-3 bg-[#f7f7f6] rounded-xl"><strong className="block uppercase font-display">Challenge</strong><span className="text-zinc-600">{call.challenge}</span></div><div className="p-3 bg-[#f7f7f6] rounded-xl"><strong className="block uppercase font-display">Tactical Win</strong><span className="text-zinc-600">{call.tacticalWin}</span></div></div><button type="button" onClick={()=>setExpanded(expanded===call.id?null:call.id)} className="mt-4 flex items-center gap-2 text-xs font-display font-extrabold uppercase text-[#0077b6]">{expanded===call.id?'Hide':'Show'} Transcript <ChevronDown className={`w-4 h-4 transition-transform ${expanded===call.id?'rotate-180':''}`}/></button>{expanded===call.id&&<div className="mt-4 space-y-2 border-t border-zinc-100 pt-4">{call.transcript.map((line,idx)=><div key={idx} className="text-xs leading-relaxed"><span className="font-mono text-zinc-400 mr-2">{line.time}</span><strong className="font-display uppercase mr-2">{line.speaker}:</strong><span className="text-zinc-600">{line.text}</span>{line.technique&&<span className="ml-2 text-[#0077b6] font-bold">[{line.technique}]</span>}</div>)}</div>}</article>)}{error&&<div className="p-3 rounded-xl bg-amber-50 border border-amber-200 text-xs text-amber-800 flex items-center gap-2"><Volume2 className="w-4 h-4"/>{error}</div>}</div>;
}
