import React, { useEffect, useState } from 'react';
import { Calendar, Menu, X, Linkedin, MessageCircle } from 'lucide-react';
import FlynnLogo from './FlynnLogo';
import { PageRoute } from '../types';

export default function Navbar({ currentPage, onNavigate, onOpenBooking }: { currentPage: PageRoute; onNavigate: (p: PageRoute) => void; onOpenBooking: () => void }) {
 const [open, setOpen] = useState(false); const [scrolled, setScrolled] = useState(false);
 useEffect(() => { const fn=()=>setScrolled(scrollY>30); addEventListener('scroll',fn); return()=>removeEventListener('scroll',fn); },[]);
 const items: [string,PageRoute][] = [['Home','home'],['Hear My Opener','calls'],['Experience','experience'],['References','references'],['Playbook','playbook'],['Leadership','leadership'],['Contact','contact']];
 const go=(p:PageRoute)=>{setOpen(false);onNavigate(p)};
 return <header className={`fixed top-0 z-50 w-full border-b transition-all ${scrolled||currentPage!=='home'?'border-slate-200 bg-white/95 shadow-sm backdrop-blur':'border-transparent bg-transparent'}`}><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-3 sm:px-6"><button onClick={()=>go('home')} aria-label="Go to Flynn home"><FlynnLogo size="sm" variant="dark"/></button><nav className="hidden lg:flex items-center gap-1 rounded-full border border-slate-200 bg-slate-50/90 p-1">{items.map(([label,route])=><button key={route} onClick={()=>go(route)} className={`nav-link ${currentPage===route?'active':''}`}>{label}</button>)}</nav><div className="hidden items-center gap-2 sm:flex"><a className="icon-btn" href="https://www.linkedin.com/in/fjpontino" target="_blank" rel="noreferrer" aria-label="LinkedIn"><Linkedin size={16}/></a><a className="icon-btn" href="https://discord.com/" target="_blank" rel="noreferrer" aria-label="Discord flynn30"><MessageCircle size={16}/></a><button onClick={onOpenBooking} className="btn-primary"><Calendar size={15}/> Schedule Intro</button></div><div className="flex items-center gap-2 lg:hidden"><button onClick={onOpenBooking} className="btn-primary px-3 py-2">Intro</button><button onClick={()=>setOpen(!open)} className="rounded-xl p-2" aria-label="Toggle navigation">{open?<X/>:<Menu/>}</button></div></div>{open&&<div className="border-t bg-white p-4 lg:hidden"><div className="grid grid-cols-2 gap-2">{items.map(([label,route])=><button key={route} onClick={()=>go(route)} className={`nav-mobile ${currentPage===route?'active':''}`}>{label}</button>)}</div><button onClick={onOpenBooking} className="btn-primary mt-3 w-full justify-center">Schedule 15-Minute Intro</button></div>}</header>;
}
